### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [Kotuhan/kottans_hw#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by Kotuhan** [comment]
GitBranching пройден.
Ссылка на скрин:
https://github.com/Kotuhan/kottans_hw/commit/61a0f963f5dbfc04ee6e541c1f8e92d38de0fc4c

**Comment by sudodoki** [comment]
👍
